config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get "posts/index"
  get "posts/show"
  devise_for :users
  authenticate :user, ->(u) {u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end
  post "hello", to:"pages#fetch"
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def contact
  end
  def fetch
    FetchJob.perform_at(10.seconds.from_now)
  end
end

app/controllers/posts_controller.rb
require 'json'
class PostsController < ApplicationController
  def index
    @response = ApiHandler.new.get_posts
    @posts = JSON.parse(@response.body);
    # puts @posts

    @posts.each do |post|
      FetchJob.perform_async(post['title'],post['body'])
end

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer</title>
</head>
<body>
    <footer class="footer">
        <div class="container">
            <section>
                <form action="">
                    <div class="form-row">
                        <div class="form-group">
                            <p>
                                <strong>Sign up for our newsletter</strong>
                            </p>
                        </div>

                        <div class="form-group">
                            <div class="form-outline">
                                <input type="email" id="email" class="form-control" placeholder="Email address" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn-submit">
                                Subscribe
                            </button>
                        </div>
                    </div>
                </form>
            </section>
        </div>

        <div class="footer-bottom">
            <p>© 2020 Copyright:
            <a class="text-link" href="https://Gorails.com/">RubyonRails.com</a></p>
        </div>
    </footer>
</body>
</html>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Home", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "logout", destroy_user_session_path, data: {turbo_method: "delete" },class:"nav-link"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Upload post",posts_index_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Services
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Railsidekiq" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Example</title>
    <%= stylesheet_link_tag("contact") %>
</head>
<body>
    <div class="form-container">
        <h1>Contact Us</h1>
        <form>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <input type="text" id="firstName" placeholder="First Name" required />
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <input type="text" id="lastName" placeholder="Last Name" required />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="text" id="companyName" placeholder="Company Name" required />
            </div>
            <div class="form-group">
                <input type="text" id="address" placeholder="Address" required />
            </div>
            <div class="form-group">
                <input type="email" id="email" placeholder="Email" />
            </div>
            <div class="form-group">
                <input type="number" id="phone" placeholder="Phone" required />
            </div>
            <div class="form-group">
                <textarea id="additionalInfo" placeholder="Additional Information" required></textarea>
            </div>
            <div class="form-check">
                <input type="checkbox" id="createAccount" Unchecked />
                <label for="createAccount">Create an account?</label>
                </div>
                <div class="button">
                <button type="button" class="btn">Send</button>
            </div>
        </form>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<%= button_to "say Hello Async",  hello_path,remote:true %>
<% if current_user %>
    <p>Hello <%= current_user.email %>!</p>

<% if current_user.admin? %>
There are <%= User.count %> users in the system.
<% end %>
<%= link_to "Monitor Jobs", sidekiq_web_path %>
<p>You have successfully authenticated with your Devise account.
You are now ready to interact with this application.
</p>
 <% else %>
 <p>You are not signed in.</p>
<%= link_to "Sign Up!", new_user_registration_path %>
<br/>
<%= link_to "login", new_user_session_path %>
<% end %>

app/views/posts/index.html.erb
 <%= stylesheet_link_tag("index") %>
<h1 align="center">Posts</h1>


<div class="cards-container">
  <% if @posts.any? %>
    <% @posts.each do |post| %>
    <div class="card">
      <h2><%= post["title"] %></h2>
      <p><%= post["body"] %></p>
    </div>
  <% end %>
  <% else %>
    <p>No posts found.</p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="single-post-container">
  <h1><%= @post['title'] %></h1>
  <p><%= @post['body'] %></p>

  <%= link_to 'Back to Posts', posts_path, class: 'back-link' %>
</div>